const fireflies = document.getElementById('fireflies');
for (let i = 0; i < 30; i++) {
  const dot = document.createElement('i'); dot.className = 'firefly';
  dot.style.left = `${Math.random() * 100}%`; dot.style.top = `${Math.random() * 92}%`;
  dot.style.setProperty('--x', `${-35 + Math.random() * 70}px`); dot.style.setProperty('--y', `${-40 + Math.random() * 80}px`);
  dot.style.setProperty('--time', `${5 + Math.random() * 7}s`); dot.style.setProperty('--delay', `${-Math.random() * 8}s`); fireflies.append(dot);
}
const overlay = document.getElementById('letterOverlay'); const letterButton = document.getElementById('letterButton'); const closeLetter = document.getElementById('closeLetter');
const sparkles = document.getElementById('sparkles');
function sparkle(x, y, amount = 18, hearts = false) { for (let i = 0; i < amount; i++) { const s = document.createElement('i'); s.className = `spark${hearts && i % 3 === 0 ? ' heart' : ''}`; if (hearts && i % 3 === 0) s.textContent = '♥'; s.style.left = `${x}px`; s.style.top = `${y}px`; const angle = Math.random() * Math.PI * 2, distance = 20 + Math.random() * 65; s.style.setProperty('--bx', `${Math.cos(angle) * distance}px`); s.style.setProperty('--by', `${Math.sin(angle) * distance}px`); sparkles.append(s); setTimeout(() => s.remove(), 950); } }
function openLetter() { overlay.classList.add('open'); overlay.setAttribute('aria-hidden', 'false'); document.body.style.overflow = 'hidden'; const rect = letterButton.getBoundingClientRect(); sparkle(rect.left + rect.width / 2, rect.top, 26); closeLetter.focus(); sound(523, .09); }
function shutLetter() { overlay.classList.remove('open'); overlay.setAttribute('aria-hidden', 'true'); document.body.style.overflow = ''; letterButton.focus(); sound(392, .08); }
letterButton.addEventListener('click', openLetter); closeLetter.addEventListener('click', shutLetter); overlay.addEventListener('click', e => { if (e.target === overlay) shutLetter(); }); document.addEventListener('keydown', e => { if (e.key === 'Escape' && overlay.classList.contains('open')) shutLetter(); });
document.querySelectorAll('.flower').forEach(f => f.addEventListener('click', e => { const r = e.target.getBoundingClientRect(); sparkle(r.left + r.width / 2, r.top + r.height / 2, 12, true); sound(659, .06); }));
document.querySelectorAll('.flower').forEach(f => f.addEventListener('keydown', e => { if (e.key === 'Enter' || e.key === ' ') { e.preventDefault(); f.click(); }}));
document.getElementById('surpriseButton').addEventListener('click', e => { const r = e.currentTarget.getBoundingClientRect(); sparkle(r.left + r.width / 2, r.top + r.height / 2, 30, true); e.currentTarget.textContent = 'Todo esto es para ti ✨'; setTimeout(() => e.currentTarget.innerHTML = 'Hay algo para ti <span>💛</span>', 1900); sound(784, .1); });
let audioContext, soundOn = false, ambienceTimer; const soundButton = document.getElementById('soundButton');
function sound(freq, duration) { if (!soundOn) return; audioContext ??= new (window.AudioContext || window.webkitAudioContext)(); const oscillator = audioContext.createOscillator(), gain = audioContext.createGain(); oscillator.frequency.value = freq; oscillator.type = 'sine'; gain.gain.setValueAtTime(.025, audioContext.currentTime); gain.gain.exponentialRampToValueAtTime(.001, audioContext.currentTime + duration); oscillator.connect(gain).connect(audioContext.destination); oscillator.start(); oscillator.stop(audioContext.currentTime + duration); }
soundButton.addEventListener('click', () => { soundOn = !soundOn; soundButton.setAttribute('aria-pressed', soundOn); document.getElementById('soundText').textContent = soundOn ? 'Sonido activo' : 'Ambiente'; if (soundOn) { sound(440, .16); ambienceTimer = setInterval(() => sound([392, 440, 523, 587][Math.floor(Math.random() * 4)], .55), 4300); } else clearInterval(ambienceTimer); });
